version: '3.1'

networks:
    app:

services:
    postgres:
        image: postgres:11-alpine
        environment:
            POSTGRES_USER: bidoomy
            POSTGRES_PASSWORD: sFmhBdJxNY9AGHdbsFmhBdJxNY9AGHdb
            POSTGRES DB: bidoomy
        ports:
          - '32800:5432'
        volumes:
          - postgres_database:/var/lib/postgresql/data
        networks:
          - app

    redis:
        image: redis:5-alpine
        ports:
          - '32798:6379'
        networks:
          - app

    php:
        build:
          context: .
          dockerfile: docker/php/Dockerfile
        restart: on-failure
        env_file:
          - .env
        depends_on:
          - postgres
        networks:
          - app

    nginx:
        image: nginx:stable-alpine
        restart: on-failure
        depends_on:
          - php
        volumes:
          - './public/:/usr/src/app'
          - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
          - './data/certs:/etc/nginx/certs'
        ports:
          - '80:80'
          - '443:443'
        networks:
          - app
volumes:
   postgres_database:
       external: true
